
name: Auto-release

on:
  push:
    branches: [ master ]
    paths: 'manifest.json'
jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check if version has been updated
        id: checkVersion
        uses: EndBug/version-check@v1

        with:
          diff-search: true
          file-name: ./manifest.json
          # Only needed when running the action on private repostiories
          token: ${{ secrets.PRIVATE_TOKEN }}

      - name: Version doesn't change
        if: steps.checkVersion.outputs.changed != 'true'
        uses: andymckay/cancel-action@0.2

      - name: Get Changelog Entry
        id: changelog
        uses: mindsers/changelog-reader-action@v2
        with:
          version: Unreleased

      - name: Create Tag
        if: steps.checkVersion.outputs.changed == 'true'
        uses: negz/create-tag@v1
        with:
          version: v${{ steps.checkVersion.outputs.version }}
          token: ${{ secrets.PRIVATE_TOKEN }}

      - name: Create Release
        if: steps.checkVersion.outputs.changed == 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PRIVATE_TOKEN }}
        with:
          tag_name: v${{ steps.checkVersion.outputs.version }}
          release_name: v${{ steps.checkVersion.outputs.version }}
          body: ${{ steps.changelog.outputs.changes }}

      - name: Update Changelog
        if: steps.checkVersion.outputs.changed == 'true'
        run: sed -i "/^## \[Unreleased\]/a\\\n\## [${{ steps.checkVersion.outputs.version }}] - $(date +%Y-%m-%d)" CHANGELOG.md

      - name: Commit Changelog update
        if: steps.checkVersion.outputs.changed == 'true'
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG.md (v${{ steps.checkVersion.outputs.version }})" -a

      - name: Push Changelog update
        if: steps.checkVersion.outputs.changed == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PRIVATE_TOKEN }}
          branch: ${{ github.ref }}
