
name: Auto-release

on:
  push:
    branches: [ master ]
    paths: 'manifest.json'
jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # https://github.com/marketplace/actions/version-check
      - name: Check if version has been updated
        id: checkVersion
        uses: EndBug/version-check@v1

        with:
          # Whether to search in every commit's diff.
          # This is useful if you often do change the version manually without including it in the title. If you only use `npm version` to bump versions then you can omit this.
          # Default: false
          diff-search: true

          file-name: ./manifest.json

          # Only needed when running the action on private repostiories
          token: ${{ secrets.PRIVATE_TOKEN }}

      - name: Version doesn't change
        if: steps.checkVersion.outputs.changed != 'true'
        uses: andymckay/cancel-action@0.2

      - name: Create Tag
        if: steps.checkVersion.outputs.changed == 'true'
        uses: negz/create-tag@v1
        with:
          version: v${{ steps.checkVersion.outputs.version }}
          token: ${{ secrets.PRIVATE_TOKEN }}
